spring.application.name=spring_restjpa_assignmentcrud
# MySQL database connection URL
#spring.datasource.url=jdbc:mysql://localhost:3306/spring

# Database username
#spring.datasource.username= root

# Database password
#spring.datasource.password= rps@123

# MySQL driver class name (for modern drivers)
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

 #spring.jpa.hibernate.ddl-auto= update
 
 #spring.jpa.show-sql= true
 spring.h2.console.enabled=true
spring.h2.console.path=/h2-ui
spring.datasource.url=jdbc:h2:mem:dcbapp
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.allow-circular-references=true